// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1qZGn5fkQig3PjdioBGKw3Z9cWdKqbUM',
    appId: '1:892989458892:web:4cc1214d9cfa6dc937b569',
    messagingSenderId: '892989458892',
    projectId: 'modchat-f6594',
    authDomain: 'modchat-f6594.firebaseapp.com',
    storageBucket: 'modchat-f6594.firebasestorage.app',
    measurementId: 'G-BFQCFHZLJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDnEJXmpjl13wQOYTV1Mf6rWMAbsFVJ64',
    appId: '1:892989458892:android:72d392f6174296f837b569',
    messagingSenderId: '892989458892',
    projectId: 'modchat-f6594',
    storageBucket: 'modchat-f6594.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp9oBxHlbsLZYHD2nqwYfzua9kkNTDHQQ',
    appId: '1:892989458892:ios:8f3c96578cebd68337b569',
    messagingSenderId: '892989458892',
    projectId: 'modchat-f6594',
    storageBucket: 'modchat-f6594.firebasestorage.app',
    iosBundleId: 'com.example.modchatMvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp9oBxHlbsLZYHD2nqwYfzua9kkNTDHQQ',
    appId: '1:892989458892:ios:8f3c96578cebd68337b569',
    messagingSenderId: '892989458892',
    projectId: 'modchat-f6594',
    storageBucket: 'modchat-f6594.firebasestorage.app',
    iosBundleId: 'com.example.modchatMvp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1qZGn5fkQig3PjdioBGKw3Z9cWdKqbUM',
    appId: '1:892989458892:web:2ae776e0e745c86137b569',
    messagingSenderId: '892989458892',
    projectId: 'modchat-f6594',
    authDomain: 'modchat-f6594.firebaseapp.com',
    storageBucket: 'modchat-f6594.firebasestorage.app',
    measurementId: 'G-WL326BYFYF',
  );
}
